version: '3.8'

volumes:
  mysql_data:
    name: ${VOLUME_NAME}

services:
    nginx:
      build: ./docker/nginx
      container_name: ${APP_NAME}-nginx
      volumes:
        - ./docker/nginx/laravel.conf:/tmp/laravel.template
        - ./src:/usr/share/nginx/html:rw,cached
      ports:
        - '80:80'
      depends_on:
        - php-fpm
        - mysql
      restart: always
      entrypoint: /bin/sh -c 'cat /tmp/laravel.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'

    php-fpm:
      build: ./docker/php-fpm
      container_name: ${APP_NAME}-php-fpm
      volumes:
        - ./src:/usr/share/nginx/html
      depends_on:
        - mysql

    mysql:
      build: ./docker/mariadb
      container_name: ${APP_NAME}-mysql
      volumes:
        - mysql_data:/var/lib/mysql:delegated
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      ports:
        - '3306:3306'
      restart: always
