# Pulls a slim image from Docker Hub, maintained by MySQL.
# This uses buster-slim, which is a distribution of choice to keep the docker images size smaller without sacrificing compatibility.
# Tag is specific as much as possible to reduce unexpected changes.

FROM mariadb:10.5

# Author of this image.
LABEL maintainer="andy@spacemeld.com"

CMD ["mysqld"]
